<a href="https://colab.research.google.com/github/QidiLiu/DL_by_Hand/blob/main/01_DL_Basics/01_05_%E7%B6%AB%E6%80%A7%E4%BB%A3%E6%95%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 线性代数基础

![](https://github.com/QidiLiu/DL_by_Hand/blob/main/img/01_05-01.png?raw=1)

![](https://github.com/QidiLiu/DL_by_Hand/blob/main/img/01_05-02.png?raw=1)

![](https://github.com/QidiLiu/DL_by_Hand/blob/main/img/01_05-03.png?raw=1)

![](https://github.com/QidiLiu/DL_by_Hand/blob/main/img/01_05-04.png?raw=1)

![](https://github.com/QidiLiu/DL_by_Hand/blob/main/img/01_05-05.png?raw=1)

![](https://github.com/QidiLiu/DL_by_Hand/blob/main/img/01_05-06.png?raw=1)

![](https://github.com/QidiLiu/DL_by_Hand/blob/main/img/01_05-07.png?raw=1)

![](https://github.com/QidiLiu/DL_by_Hand/blob/main/img/01_05-08.png?raw=1)

![](https://github.com/QidiLiu/DL_by_Hand/blob/main/img/01_05-09.png?raw=1)

![](https://github.com/QidiLiu/DL_by_Hand/blob/main/img/01_05-10.png?raw=1)

![](https://github.com/QidiLiu/DL_by_Hand/blob/main/img/01_05-11.png?raw=1)

![](https://github.com/QidiLiu/DL_by_Hand/blob/main/img/01_05-12.png?raw=1)

![](https://github.com/QidiLiu/DL_by_Hand/blob/main/img/01_05-13.png?raw=1)

### 綫性代數實現

標量由只有一個元素的張量表示

In [ ]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

向量可看作由標量值組成的列表

In [ ]:
x = torch.arange(4, dtype=torch.float32)
x

tensor([0., 1., 2., 3.])

可通過張量的索引來訪問向量中的任一元素

In [ ]:
x[3]

tensor(3.)

通過指定長寬，創建一個形狀為m*n的矩陣

In [ ]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩陣的轉置

In [ ]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

對於對稱矩陣 (symmetric matrix)，原矩陣等於其轉置

In [ ]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [ ]:
B.T, B == B.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]), tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

類似的，還可以構建超過2維的多維矩陣

In [ ]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

給定相同尺寸的任意兩個張量，任何按元素二元運算的結果都將是相同形狀的張量

In [ ]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 用clone才能為張量B分配新内存
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]), tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

兩矩陣按元素乘法稱爲*哈達瑪積* (Hadamard product)

In [ ]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

在用sum求和時，可指定參數來保持軸數不變

In [ ]:
sum_A = A.sum(dim=1, keepdims=True) # 保持維度數不變是進行廣播的前提
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

通過廣播將A除以sum_A

In [ ]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

用cumsum可沿某個軸計算A元素的纍積總和

In [ ]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

點積dot是相同位置的按元素乘積的和

In [ ]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [ ]:
torch.sum(x * y)

tensor(6.)

矩陣向量積Ax是一個長度爲m的列向量

In [ ]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

我們可將矩陣-矩陣乘法AB看作簡單地執行m次矩陣向量積，并將結果堆叠在一起，形成一個n*m矩陣

In [ ]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

L2範數是向量元素平方和的平方根（比如算距離時常用這種）

In [ ]:
u = torch.tensor([3.0, -4.0])
torch.norm(u) # Frobenius norm

tensor(5.)

L1範數表示為向量元素的絕對值之和

In [ ]:
torch.abs(u).sum()

tensor(7.)